feat: prisma schema 추가
SystemConsultantGroup/foodhub-backend pull request #2
Opened 2023-08-08 06:58 UTC by taeboranger

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- prisma schema 작성

## 비고

2023-08-08 07:30 UTC, kanghoon-dev requested changes
오타 몇 개, 네이밍 및 타입 관련한 코멘트들입니다:)

스키마에서 빠진 값은 없는 것 같아요!

2023-08-08 07:30 UTC, kanghoon-dev commented on prisma/schema.prisma
> +  id               Int          @id @default(autoincrement())
id 값들 bigint 사용하는건 어떨까요?

2023-08-08 07:30 UTC, kanghoon-dev commented on prisma/schema.prisma
> +  updatedAt        DateTime     @updatedAt
아래와 같이 수정하는 것이 prisma studio 에서 작업하기 편하다고 했던 것 같습니다 :)

```suggestion
  updatedAt        DateTime     @default(now()) @updatedAt
```

2023-08-08 07:30 UTC, kanghoon-dev commented on prisma/schema.prisma
> +  area       EmdAreas     @relation(fields: [areaId], references: [id])
`@relation` 이 붙어있는 것들은 맨 아래쪽으로, 또는 Array(?) 바로 위쪽으로 넣어 주는게 어떨까요? 모여있는게 좀 보기 편하지 않을까 싶어서요. 
다만 이렇게 하면 id랑 떨어지는 문제가 있긴 하네요... @R3gardless @yesjuhee  의견 부탁드립니다 :)

2023-08-08 07:30 UTC, hoon5083 commented on prisma/schema.prisma
> +  Vote       Vote[]
one to many 관계이면(타입이 Array 이면) 네이밍 복수형이 좋을 거 같아요
다른 부분도 확인해서 적용하면 좋을 듯 합니다!

2023-08-08 07:30 UTC, hoon5083 commented on prisma/schema.prisma
> +model Item {
VoteItem으로 수정하면 어떨까요?

2023-08-08 07:30 UTC, hoon5083 commented on prisma/schema.prisma
> +  exprieAt    DateTime?
오타 같습니당 
```suggestion
  expireAt    DateTime?
```

2023-08-08 07:30 UTC, hoon5083 commented on prisma/schema.prisma
> +  rerestaurantName String?
오타 같습니당 
```suggestion
  restaurantName String?
```

2023-08-08 07:30 UTC, hoon5083 commented on prisma/schema.prisma
> +  scroe            Int
오타 같습니당
```suggestion
  score            Int
```

2023-08-08 07:30 UTC, hoon5083 commented on prisma/schema.prisma
> +model ItemUser {
many to many 관계 만들기 위한 테이블들은 특별한 의미를 지니는 테이블이 아니라면 postfix 하나 넣어주는게 어떨까요?
Associative에서 따와서, `VoteItemUserA` 이런 식으로...?

만약 PK, FK 두개 + 생성/수정/삭제 이외의 정보를 가지는 테이블이면 네이밍을 의미 있는 네이밍을 넣어주는 것도 괜찮을 것 같습니다
UserGroup 같은경우 Registration과 같이 말이죠

2023-08-08 07:30 UTC, hoon5083 commented on prisma/schema.prisma
> +  default_photo_id Int          @db.TinyInt
이거 @default(dbgenerated(...)) 사용해보면 어떨까요?
관련 문서입니다.

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#dbgenerated

2023-08-08 07:36 UTC, taeboranger commented on prisma/schema.prisma
> +  id               Int          @id @default(autoincrement())
bigint도 생각은 해봤는데 규모가 그렇게까지 커질까? 라고 생각했었습니다. 근데 나중에 bigint로 바꿀 바에야 처음부터 bigint로 가는게 괜찮을 수도 있겠네요

2023-08-08 07:37 UTC, taeboranger commented on prisma/schema.prisma
> +  Vote       Vote[]
VSC prisma 익스텐션이 알아서 포맷팅을 저렇게 하길래 내비뒀는데 복수형이 좋긴 하겠네요 반영하겠습니다

2023-08-08 07:39 UTC, kanghoon-dev commented on prisma/schema.prisma
> +  id               Int          @id @default(autoincrement())
네넵 삭제하고 다시만들고 하는 것까지 생각하면... 혹시 모르니까요 ㅎㅎ

2023-08-08 09:37 UTC, hoon5083 commented
label 추가해주세요 :)

2023-08-08 15:40 UTC, taeboranger commented on prisma/schema.prisma
> +  id               Int          @id @default(autoincrement())
[반영 완료]

2023-08-08 15:40 UTC, taeboranger commented on prisma/schema.prisma
> +  updatedAt        DateTime     @updatedAt
[반영 완료]

2023-08-08 15:40 UTC, taeboranger commented on prisma/schema.prisma
> +  Vote       Vote[]
[반영 완료]

2023-08-08 15:40 UTC, taeboranger commented on prisma/schema.prisma
> +model Item {
[반영 완료]

2023-08-08 15:40 UTC, taeboranger commented on prisma/schema.prisma
> +model ItemUser {
[반영 완료]

2023-08-08 15:41 UTC, taeboranger commented on prisma/schema.prisma
> +  default_photo_id Int          @db.TinyInt
[반영 완료]

2023-08-09 01:51 UTC, hantaihe commented on prisma/schema.prisma
> +  birth_year       DateTime?
이 3개의 column만 snake_case로 하신 이유가 있으신가요?

2023-08-09 06:21 UTC, taeboranger commented on prisma/schema.prisma
> +  birth_year       DateTime?
받아쓰기 하다가 그만...
반영 완료

2023-08-09 09:41 UTC, hoon5083 commented on prisma/schema.prisma
> +model ItemUser {
RestaurantTag 부분은 그냥 놓치신걸까요? 의도적인 거였다면 말씀해주시고, 놓치신거면 수정후에 노티 부탁드립니다 :)

2023-08-09 09:48 UTC, taeboranger commented on prisma/schema.prisma
> +model ItemUser {
놓쳤네요 마저 수정했습니다! 감사합니다

2023-08-09 10:14 UTC, hoon5083 commented on prisma/schema.prisma
> +  area       EmdAreas     @relation(fields: [areaId], references: [id])
이거 한번씩 확인하시고, 컨벤션 정해지면 resolve 하고 approve하겠습니다!
@taeboranger @yesjuhee @R3gardless

2023-08-09 13:08 UTC, R3gardless commented on prisma/schema.prisma
> +  password       String
카카오 로그인을 할 때 password field 가 null 일수도 있긴 한데 추후 확장성을 위해서 일단 임의의 값으로 넣는게 좋겠네요.

2023-08-09 13:19 UTC, kanghoon-dev commented on prisma/schema.prisma
> +  password       String
어유 그러게요 자체 로그인 구현 계획의 흔적이.... 음... 이 컬럼 nullable 로 해도 될것 같긴 합니다! 자체 회원가입 유저와 카카오로 가입한 유저를 구분하는 기준을 password 컬럼의 null 여부로 하면 되지 않을까 싶어요

2023-08-09 13:26 UTC, taeboranger commented on prisma/schema.prisma
> +  area       EmdAreas     @relation(fields: [areaId], references: [id])
저는 id랑 relation이랑 붙어있는게 좀 보기 편하지 않을까 합니다

2023-08-09 13:29 UTC, taeboranger commented on prisma/schema.prisma
> +  password       String
반영 완료

2023-08-09 14:39 UTC, yesjuhee commented on prisma/schema.prisma
> +  area       EmdAreas     @relation(fields: [areaId], references: [id])
고유한 속성들을 우선 배치하는 느낌으로 `@relation` 붙어있는 것들은 Array(?) 위쪽으로 넣어주는게 좋지 않을까에 한표 하겠습니다!

지금 `SiggArea`와 `EmdArea`는 뒤쪽에 `@relation` 들을 배치하고 있고 `Group`은 중간에 들어가 있어서 위치의 통일을 할 필요는 있어 보입니다.

2023-08-09 16:40 UTC, R3gardless commented on prisma/schema.prisma
> +  email          String
email 부분에 unqiue 를 추가하는 게 좋지 않을까요??

2023-08-10 11:15 UTC, hoon5083 commented on prisma/schema.prisma
> +  rerestaurantName String?
엏... 왜인지 모르겠는데 이거 반영이 안된거 같아요! 확인 부탁드립니다 :)

2023-08-10 11:15 UTC, hoon5083 commented on prisma/schema.prisma
> +  scroe            Int
엏... 왜인지 모르겠는데 이거 반영이 안된거 같아요! 확인 부탁드립니다 :)

2023-08-10 11:19 UTC, hoon5083 commented on prisma/schema.prisma
> +  rerestaurantName String?
아 이거 강제 푸시 하면서 날아간거 같네요 ㅋㅋ 수정 부탁드립니다 :)

2023-08-10 11:19 UTC, hoon5083 commented on prisma/schema.prisma
> +  scroe            Int
마찬가지로 수정 부탁드립니다 :)

2023-08-10 11:22 UTC, taeboranger commented on prisma/schema.prisma
> +  rerestaurantName String?
반영 완료

2023-08-10 11:22 UTC, taeboranger commented on prisma/schema.prisma
> +  scroe            Int
반영 완료

2023-08-10 11:23 UTC, hoon5083 commented on prisma/schema.prisma
> +  rerestaurantName String?
14c38a780ada4610807b051d23b1ae2edcbd4fff 여기서 다시 되돌아 가는 수정이 일어났네요...? 확인 부탁드립니다!

2023-08-10 11:38 UTC, hoon5083 commented on prisma/schema.prisma
> +  area       EmdAreas     @relation(fields: [areaId], references: [id])
음...아래와 같은 순서는 어떨까요?
```
model Restaurant {
  id              String           @id @default(uuid())
  name            String
  address         String?
  link            String?
  delivery        Boolean?
  comment         String?
  capacity        Int?             @db.TinyInt
  openingHour     String?
  recommendedMenu String?
  orderTip        String?
  isActivated     Boolean
  createdAt       DateTime         @default(now())
  updatedAt       DateTime         @default(now()) @updatedAt
  deletedAt       DateTime?
  RestaurantTagAs RestaurantTagA[]
  Files           File[]
  Reviews         Review[]
  VoteItems       VoteItem[]
  userId          BigInt
  groupId         BigInt
  categoryId      BigInt
  user            User             @relation(fields: [userId], references: [id])
  group           Group            @relation(fields: [groupId], references: [id])
  category        Category         @relation(fields: [categoryId], references: [id])
}
```

PK, 일반적인 column, 날짜, Array, FK, relation 의 순서로 들어가면 좀 깔끔할 것 같습니다.
relation 바로 윗줄에 주석 추가해주는 것도 나쁘지 않을 것 같구요

2023-08-10 11:40 UTC, hoon5083 commented on prisma/schema.prisma
> +  email          String
음... 저도 그게 좋을 것 같습니다! 후에 다른 소셜 로그인을 추가하게 되면, 해당 이메일로 가입된 계정이 또 있음을 응답으로 알려줘야겠군요!

2023-08-10 11:41 UTC, taeboranger commented on prisma/schema.prisma
> +  area       EmdAreas     @relation(fields: [areaId], references: [id])
저는 이거 괜찮은 것 같습니다

2023-08-10 11:42 UTC, taeboranger commented on prisma/schema.prisma
> +  email          String
반영 완료

2023-08-10 11:43 UTC, hoon5083 commented on prisma/schema.prisma
> +  email          String
@R3gardless 반영된거 확인해주시고, 본 스레드 resolve 부탁드립니다! 다른 문제 없다면 approve도 함께요 :)

2023-08-10 11:49 UTC, taeboranger commented on prisma/schema.prisma
> +  area       EmdAreas     @relation(fields: [areaId], references: [id])
일단 이대로 반영해봤으니 한번 느낌들 확인해 보시면 될 것 같습니다

2023-08-10 12:01 UTC, hoon5083 commented on prisma/schema.prisma
> +  area       EmdAreas     @relation(fields: [areaId], references: [id])
저는 확인했습니다! 다른 분들 반응해주시면 본 스레드 resolve할게요

2023-08-10 14:52 UTC, hoon5083 approved these changes
수고하셨습니다!

2023-08-11 04:42 UTC, yesjuhee commented on prisma/schema.prisma
> +// user 테이블 정의
이 주석은 삭제해도 될 것 같습니다!

2023-08-11 10:39 UTC, R3gardless approved these changes

2023-08-11 11:04 UTC, hoon5083 commented on prisma/schema.prisma
> +// user 테이블 정의
수정된 걸로 보여서, 본스레드 resolve 하겠습니다!
마지막 스레드네요 :) @taeboranger merge 해주시면 됩니다!

2023-08-11 11:15 UTC, merged