feat: Kakao auth API 추가
SystemConsultantGroup/foodhub-backend pull request #5
Opened 2023-08-20 14:07 UTC by R3gardless

## 체크 리스트

- [ x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [ x] Target Branch를 올바르게 설정했나요?
- [ x] Label을 알맞게 설정했나요?

## 작업 내역

- 카카오 로그인 기반 Guard 구현 완료
- @UseGuards(AuthGuard("kakao")) 로 로그인 여부 및 해당 유저 kakaoID 가져올 수 있음.
- CommonResponseDTO 개발 → message : string, success : boolean 기본값

## 비고

2023-08-20 17:24 UTC, yesjuhee approved these changes
수고하셨습니다!

2023-08-21 07:32 UTC, hoon5083 requested changes
이전 플젝에서 인증 로직을 직접 담당하질 않아 조금 이해가 부족한 부분도 있을거 같아서, @hantaihe 님이 혹시 추가로 코멘트 주시면 해당 내용보고 approve 하겠습니다 :)

2023-08-21 07:32 UTC, hoon5083 commented on src/auth/auth.controller.ts
> +  @UseGuards(AuthGuard("kakao")) // Kakao 로그인 테스트
```typescript
/**
* @TODO: kakao 로그인 구현
*/ 
```

와 같이 사용하시면 IDE 에서 To do list를 모아줍니다 :)

2023-08-21 07:32 UTC, hoon5083 commented on src/common/dtos/common-response.dto.ts
> +export class CommonResponseDto<T = void> {
이걸 그대로 사용하려다가, 그랬을때 swagger에서 응답 형식을 제공할 수 없는 문제가 있어서 모든 응답에 dto를 따로 구성하는 편이 어떨까 싶긴 했습니다. @yesjuhee @taeboranger 확인 부탁드립니다 :)

@hantaihe 혹시 의견 주실 수 있으실지...ㅎㅎ 함께 멘션합니다

관련 슬랙 링크
https://systemconsult-vqd4955.slack.com/archives/C05EW6Q949E/p1692085827258509?thread_ts=1692085696.768779&cid=C05EW6Q949E

2023-08-21 23:58 UTC, hantaihe commented on src/common/dtos/common-response.dto.ts
> +export class CommonResponseDto<T = void> {
맞습니다 타입이 런타임 때 정해지니까 swagger에서 인식을 못하더라구요
그래서 저도 응답마다 dto를 따로 구성하고, 공통으로 묶일 수 있는 구조는 generic 안 쓰고 extends로 사용합니다.

2023-08-22 05:28 UTC, hoon5083 commented on src/common/dtos/common-response.dto.ts
> +export class CommonResponseDto<T = void> {
그럼 이 부분 수정 부탁드립니다 @R3gardless

2023-08-22 05:31 UTC, hoon5083 commented
본 PR의 가드를 적용하고 메소드 내부에서는 어떻게 토큰으로부터의 유저 정보를 가져오나요? @R3gardless

2023-08-22 06:29 UTC, R3gardless commented on src/common/dtos/common-response.dto.ts
> +export class CommonResponseDto<T = void> {
@hoon5083 Access Token 을 Authroization header 로 보내서 더 이상 ResponseDTO 를 사용하지 않는데 그냥 삭제해도 괜찮을까요?

2023-08-22 07:17 UTC, hoon5083 commented on src/common/dtos/common-response.dto.ts
> +export class CommonResponseDto<T = void> {
네넵 그냥 삭제하는 편이 더 좋을 듯 합니다!

2023-08-27 15:37 UTC, R3gardless commented
로직 변경된 Guard 구현하여 PR 다시 만들겠습니다

2023-08-27 15:38 UTC, closed without merging