feat: User OAuth2 관련 정보 추가
SystemConsultantGroup/foodhub-backend pull request #6
Opened 2023-08-25 07:26 UTC by R3gardless

Related to #{이슈 번호 기입}

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- User 정보에 Oauth2 ID 와 Provider (kakao, local, 기타 등등) 정보 추가했습니다.
- Provider 관련 enums common folder 내에 만들었습니다.

## 비고

2023-08-26 06:08 UTC, hoon5083 requested changes
하나만 수정된거 확인하면 approve할게요!

2023-08-26 06:08 UTC, hoon5083 commented on src/common/enums/user-provider.enum.ts
> +    LOCAL = 'LOCAL',
자체로그인 없어서, 일단  LOCAL도 빼두는게 좋지 않을까 싶습니다!

2023-08-26 06:10 UTC, hoon5083 commented
hotfix는 배포 이후에 급한 수정시 사용하시면 됩니다! PR 머지 규칙이 달라서, 다른 네이밍이 좋을거 같아요. 혹시 가능하면 변경해두시면 좋겠습니다

develop 배포이전에는 feature가 기본이라고 생각하시면 될 것 같습니다!

2023-08-26 14:41 UTC, R3gardless commented on src/common/enums/user-provider.enum.ts
> +    LOCAL = 'LOCAL',
넵 수정했습니다
\

2023-08-29 12:54 UTC, hoon5083 approved these changes
LGTM 입니다!

2023-08-30 07:17 UTC, closed without merging