feat: kakao-login Guard Strategy 구현
SystemConsultantGroup/foodhub-backend pull request #7
Opened 2023-08-27 15:41 UTC by R3gardless

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- /auth/kakao/login 접근 시 카카오 로그인 페이지로 redirect
- callback 함수를 통해 Kakao Id Token cookie 에 담아 보내기
- Caching 을 이용한 Kakao Public Key 저장 (86400sec = 1일)
- Guard 에서 Oauth2Strategy Validate 함수를 사용하여 request.body.oauth2Id 에 해당 카카오 유저 sub 저장

## 비고

- Swagger 에서 redirect API 호출하면 에러가 나서 URI 상에 /auth/kakao/login 으로 접근하시면 자동으로 카카오 로그인 페이지로 redirect 됩니다.

2023-08-28 00:44 UTC, taeboranger commented
이전 pr에서 common response dto 제거한게 남아있는 것 같습니다

2023-08-29 12:52 UTC, hoon5083 requested changes
몇가지 수정제안이 있습니다!

2023-08-29 12:52 UTC, hoon5083 commented on src/auth/auth.controller.ts
> +  }
이건 로컬에서 테스트용으로 남겨두신건가요?

2023-08-29 12:52 UTC, hoon5083 commented on src/auth/auth.service.ts
> +    const sub = decodedToken.sub as string;
혹시 as string 사용하신 이유가 있을까요? 미리 decode된 token의 타입을 다른데 정의해두면 어떨까 싶어요

2023-08-29 12:52 UTC, hoon5083 commented on src/auth/guards/oauth2.guard.ts
> +    const request: Request = context.switchToHttp().getRequest();
요기 Request 타입 명시는 기본적으로 추론되면 빼주시면 좋을거 같습니다 :)

2023-08-29 12:54 UTC, R3gardless commented on src/auth/auth.controller.ts
> +  }
넵넵 Oauth2Guard return 값 확인하려고 두었던 건데 필요 없으시면 삭제하도록 하겠습니다

2023-08-29 13:00 UTC, R3gardless commented on src/auth/auth.service.ts
> +    const sub = decodedToken.sub as string;
기본적인 decodeToken.sub 의 타입이 string | (() => string) 로 지정되어 있어서 findUnique 에서 타입 에러를 일으키길래 강제로 string 으로 지정해줬는데 혹시 다른 해결방안이 있을까요?

2023-08-29 13:02 UTC, R3gardless commented on src/auth/guards/oauth2.guard.ts
> +    const request: Request = context.switchToHttp().getRequest();
반영 완료

2023-08-29 13:33 UTC, hoon5083 commented on src/auth/auth.service.ts
> +    const sub = decodedToken.sub as string;
음... 애매하네요.. 조건문 추가해서 타입 확인하면 어떨까요?

2023-08-29 13:33 UTC, kanghoon-dev commented on src/auth/auth.controller.ts
> +  }
네네 삭제하면 좋을거 같습니다

2023-08-29 13:49 UTC, R3gardless commented on src/auth/auth.service.ts
> +    const sub = decodedToken.sub as string;
반영 완료

2023-08-29 13:49 UTC, R3gardless commented on src/auth/auth.controller.ts
> +  }
반영 완료

2023-08-29 13:51 UTC, hoon5083 approved these changes
수고하셨습니다!

2023-08-29 13:52 UTC, taeboranger approved these changes
수고하셨습니다

2023-08-29 14:20 UTC, merged